import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import styles from './layout.module.css';

const HSESans = localFont({
	src: [
		{
			path: '../fonts/HSESans-Regular.otf',
			weight: '400',
		},
		{
			path: '../fonts/HSESans-Bold.otf',
			weight: '700',
		},
		{
			path: '../fonts/HSESans-SemiBold.otf',
			weight: '600',
		},
	],
});

export const metadata: Metadata = {
	title: 'MIEM cabinet',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={HSESans.className}>
				<div className={styles.wrapper}>
					<header className={styles.header}>header</header>
					<div className={styles.sidebar}>sidebar</div>
					<div className={styles.body}>{children}</div>
					<footer className={styles.footer}>footer</footer>
				</div>
			</body>
		</html>
	);
}
